import { Image as ImageType } from '@/types';
import fetcher from '@/utils/fetcher';
import Head from 'next/head';
import { subDays, format } from 'date-fns';
import ImageOfTheDay from '@/components/ImageOfTheDay';
import LastTenDaysImages from '@/components/LastTenDaysImagesProps';

type HomeProps = {
  imageOfTheDay: ImageType;
  last10DaysImages: ImageType[];
};

export default function Home({ imageOfTheDay, last10DaysImages }: HomeProps) {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <title>Imágenes - NASA Api</title>
      </Head>
      <main className="sm:p-10">
        <ImageOfTheDay {...imageOfTheDay} />
        <LastTenDaysImages images={last10DaysImages} />
      </main>
    </>
  );
}

export async function getStaticProps() {
  try {
    const end = new Date();
    const start = subDays(end, 9);
    const startDate = format(start, 'yyyy-MM-dd');
    const endDate = format(end, 'yyyy-MM-dd');

    const imageOfTheDay = await fetcher();
    const last10Days = await fetcher(
      `&start_date=${startDate}&end_date=${endDate}`
    );

    const last10DaysImages = last10Days.filter(
      (image: ImageType) => image.media_type === 'image'
    );

    return {
      props: {
        imageOfTheDay,
        last10DaysImages,
      },
      revalidate: 60 * 60 * 24,
    };
  } catch (error) {
    console.error(error);
  }
}
